### ISSUE TITLE
is it possible for the receiver thread hanging forever?

### ISSUE THREAD

**Issue by Daniel-Xu** [m-ou-se/rust-atomics-and-locks#10]
### The content that the question is about

![2023-01-30 at 8 36 PM](https://user-images.githubusercontent.com/548144/215479156-9dd84910-df00-444d-a8c7-65b6cda985e2.png)

In [Chapter 5. Building Our Own Channels](https://marabos.nl/atomics/building-channels.html) 

the implementation is from [Safety Through Runtime Checks](https://marabos.nl/atomics/building-channels.html#safety-through-runtime-checks)

### The question

is it possible for the receiver thread hanging forever?

## my reasoning 

For `is_ready`, the sender thread stores `true` with `Release` ordering and then unpark the `Receiver` thread. 
After woken up, the receiver  thread will check the `is_ready` again. However, it's possible that the return value is still `false` because we are using simple `load`. 

This will park the receiver thread again and no other events will wake it up, thus hanging forever.

**Comment by m-ou-se** [comment]
That is a great question!

The answer is, fortunately: no, this won't hang forever. However, the reason for that is subtle and not actually fully explained in the book. (I might go a bit deeper into that in a next edition of the book.)

The reason this won't hang forever, is that `unpark()` forms a happens-before relationship with the `park()` call that it wakes up. (See the comment in the implementation [here](https://github.com/rust-lang/rust/blob/a00e24d76a9ac03b146d3bf89e2161b2466c6551/library/std/src/sys_common/thread_parking/futex.rs#L90-L92).)

I'll see if we can document that better and make it a proper guarantee.

**Comment by Daniel-Xu** [comment]
![image](https://user-images.githubusercontent.com/548144/217879446-1bfc9f68-6e73-40d8-9b9c-750a35dad3b4.png)
Thanks so much @m-ou-se , I got it now after reading the source code of `park` & `unpark`
