### ISSUE TITLE
Typo in chapter 5 summary

### ISSUE THREAD

**Issue by Imberflur** [m-ou-se/rust-atomics-and-locks#13]
### Type of error

Typo

### Location of the error

https://marabos.nl/atomics/building-channels.html#summary

### Description of the error

> Taking a non-Copy object by value can be used to prevent something to be done more than once.

Potential fix:

"Taking a non-Copy object by value can be used to prevent something ~to be~ **from being** done more than once."

(Marked as a typo but maybe this could be considered a grammer issue?)

**Comment by m-ou-se** [comment]
Thanks! Fixed.
