### ISSUE TITLE
Typo in Chapter 7 (Processor Instructions)

### ISSUE THREAD

**Issue by Imberflur** [m-ou-se/rust-atomics-and-locks#14]
### Type of error

Typo

### Location of the error

https://marabos.nl/atomics/hardware.html#instructions

### Description of the error

> A more direct option is to ask the compiler to produce assembly instead a binary by using the --emit=asm flag to rustc. 

`instead a binary` -> `instead of a binary` or `instead of binary`?

**Comment by m-ou-se** [comment]
Fixed!
