### ISSUE TITLE
Understated "worst that can happen" in Statistics Example

### ISSUE THREAD

**Issue by wurdack** [m-ou-se/rust-atomics-and-locks#18]
### Type of error

Minor technical mistake

### Location of the error

https://marabos.nl/atomics/atomics.html#example-statistics

### Description of the error

> Since the three atomic variables are updated separately, it is possible for the main thread to load the values after a thread has incremented num_done, but before it has updated total_time, resulting in an underestimate of the average. More subtly, because the Relaxed memory ordering gives no guarantees about the relative order of operations as seen from another thread, it might even briefly see a new updated value of total_time, while still seeing an old value of num_done, resulting in an overestimate of the average.

> Neither of this is a big issue in our example. The **worst that can happen is that an inaccurate average** is briefly reported to the user.

I believe the worst that can happen is you divide by zero.

**Comment by m-ou-se** [comment]
How would a division by zero occur in that example? The `total_time / n` expression is in the `else` branch of a `if n == 0`.

**Comment by wurdack** [comment]
I am 100% sure there are orders of execution where that branch isn't sitting solidly in my blind spot. Apparently reading this chapter on a Friday afternoon wasn't one of them. 🙄
