### ISSUE TITLE
Typo in Chapter 4

### ISSUE THREAD

**Issue by Daniel-Xu** [m-ou-se/rust-atomics-and-locks#3]
### Type of error

Typo

### Location of the error

https://marabos.nl/atomics/building-spinlock.html

### Description of the error

![image](https://user-images.githubusercontent.com/548144/212878498-cb6681ec-1dcb-49f8-8149-db4da8f1c14c.png)

this `is_ok` should be `is_err`.

**Comment by m-ou-se** [comment]
Thanks!

Fixed. I've also added `while` in front to make it clearer this is the loop condition.
