### ISSUE TITLE
Simple typo in Memory Ordering, Example: Lazy Initialization with Indirection

### ISSUE THREAD

**Issue by tpdickson** [m-ou-se/rust-atomics-and-locks#39]
### Type of error

Typo

### Location of the error

https://marabos.nl/atomics/memory-ordering.html#example-lazy-initialization-with-indirection

### Description of the error

In the following paragraph:

For this example, let’s say we want to maintain the non-blocking behavior, so that threads never wait for another thread, but instead race and take the value from the first thread to complete initialization. This means we still need to be able to go from "**uninitalized**" to "fully initialized" in a single atomic operation.

The bold word "uninitalized" should be "uninitialized".

**Comment by m-ou-se** [comment]
Thanks! Fixed!
