### ISSUE TITLE
Is using `Box::into_raw` maybe preferable to `Box::leak` when paired with later `Box::from_raw`?

### ISSUE THREAD

**Issue by jswalden** [m-ou-se/rust-atomics-and-locks#4]
https://github.com/m-ou-se/rust-atomics-and-locks/blob/af59f9be0744e4adc3362043307083673e30d2f2/src/ch6_arc/s1_basic.rs#L22

Examples/source in the book, when a raw pointer is needed, pair `Box::leak` with `Box::from_raw`.  Naively, I would have expected from name -- and documentation [seems to suggest similarly](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.into_raw) ("The easiest way to do this is to...") -- that it would be preferable to pair `Box::into_raw` with `Box::from_raw`.

Is there a special reason to use `Box::leak` instead of `Box::into_raw`?  I guess the former gives you a reference, which means you don't need to use `NonNull::new(ptr).unwrap()` or unsafe `NonNull::new_unchecked` maybe?  But the unpaired names (without obvious reason) are just the teensiest stumbling block for the pedant in me, more than either of those would be.

Love the book so far through chapter 6 (online so far, in theory Amazon ships my print copy any day now), this is not a complaint about book or code, just a question I haven't been able to get out of my mind since I started the chapter.  :-)

**Comment by m-ou-se** [comment]
> I guess the former gives you a reference, which means you don't need to use `NonNull::new(ptr).unwrap()` or unsafe `NonNull::new_unchecked` maybe?

Yup, that's the only reason. We should probably add a `Box::into_non_null()` or something like that.
