### ISSUE TITLE
Maybe a typo in a comment rwlock_3.rs

### ISSUE THREAD

**Issue by gurugio** [m-ou-se/rust-atomics-and-locks#46]
https://github.com/m-ou-se/rust-atomics-and-locks/blob/d945e828bd08719a2d7cb6d758be4611bd90ba2b/src/ch9_locks/rwlock_3.rs#L61C26-L61C26

I guess it checks if it's even number.

**Comment by m-ou-se** [comment]
We "make sure the state is odd" by adding one *if it's even*. So you're right that it checks if it's an even number, because then we need to change it. (To make sure it's an odd number.)
