### ISSUE TITLE
Question about correctness of example in chapter 5

### ISSUE THREAD

**Issue by mlowicki** [m-ou-se/rust-atomics-and-locks#47]
### The content that the question is about

```rust
fn main() {
    let channel = Channel::new();
    let t = thread::current();
    thread::scope(|s| {
        s.spawn(|| {
            channel.send("hello world!");
            t.unpark();
        });
        while !channel.is_ready() {
            thread::park();
        }
        assert_eq!(channel.receive(), "hello world!");
    });
}

...
/// Panics when trying to send more than one message.
pub fn send(&self, message: T) {
    if self.in_use.swap(true, Relaxed) {
        panic!("can't send more than one message!");
    }
    unsafe { (*self.message.get()).write(message) };
    self.ready.store(true, Release);
}

pub fn is_ready(&self) -> bool {
    self.ready.load(Relaxed)
}
```

### The question

How is it guaranteed that after `t.unpark()`, inside the `while` loop, the most recent value will be visible? If not, it would be possible that `unpark()` wakes up the thread, it loads the value but still sees that ready is not true and will park the current thread -  afterwards there won't be anything waking up that thread anymore.

**Comment by mlowicki** [comment]
Never mind - I've missed previously https://doc.rust-lang.org/std/thread/fn.park.html#memory-ordering which answers my questions.

Might be good to still add more explanation or at least that doc link to the book to make it clearer.

**Comment by m-ou-se** [comment]
Thanks for submitting this great question!

You're right that the book skips some details on memory ordering of park+unpark. While it was always agreed upon that examples such as the one your question is about are correct, the exact memory ordering guarantee that's now part of the documentation of `std::thread::park()` that you link to was only added after the book was released after some discussion in the Rust library team. If I ever work on a next edition of the book, I'll make sure to go a bit more into detail here.
