### ISSUE TITLE
Question about ch9 3-state mutex impl

### ISSUE THREAD

**Issue by zxch3n** [m-ou-se/rust-atomics-and-locks#5]
### The content that the question is about

Chapter 9. Building Our Own Locks > Avoid Syscalls

### The question

The unlocking is implemented like

https://github.com/m-ou-se/rust-atomics-and-locks/blob/af59f9be0744e4adc3362043307083673e30d2f2/src/ch9_locks/mutex_3.rs#L68-L74

But I don't understand why the first line of the lock function cannot load the zero value released by unlocking when other threads are waiting for it. 

https://github.com/m-ou-se/rust-atomics-and-locks/blob/af59f9be0744e4adc3362043307083673e30d2f2/src/ch9_locks/mutex_3.rs#L42-L49

For example, thread A locked the mutex, and B and C waited for the mutex. A released the mutex, while concurrently, D tried to lock to mutex. If D loads the zero value released by A with `if self.state.compare_exchange(0, 1, Acquire, Relaxed).is_err()`, D gets the lock and sets the lock state to 1. But the state should be 2 because multiple threads are waiting for it. 

Another question is if D and B acquired and released the lock, then thread C acquired the lock by 

https://github.com/m-ou-se/rust-atomics-and-locks/blob/af59f9be0744e4adc3362043307083673e30d2f2/src/ch9_locks/mutex_3.rs#L63-L65

It will set the state to 2, but the correct state should be 1 because there is no thread waiting for the mutex.

What do I miss?

**Comment by m-ou-se** [comment]
>  For example, thread A locked the mutex, and B and C waited for the mutex. A released the mutex, while concurrently, D tried to lock to mutex. If D loads the zero value released by A with `if self.state.compare_exchange(0, 1, Acquire, Relaxed).is_err()`, D gets the lock and sets the lock state to 1. But the state should be 2 because multiple threads are waiting for it.

D will indeed set the lock state to 1, but A also woke up either B or C, which will set the state back to 2 before going to sleep again:

https://github.com/m-ou-se/rust-atomics-and-locks/blob/af59f9be0744e4adc3362043307083673e30d2f2/src/ch9_locks/mutex_3.rs#L63-L65

---

> Another question is if D and B acquired and released the lock, then thread C acquired the lock by [..] It will set the state to 2, but the correct state should be 1 because there is no thread waiting for the mutex.

Indeed, and because of that we'll get one unnecessary call to `wake_one()`, as is mentioned in the book:

> This does mean that for every time a thread had to wait() while locking, it will also call wake_one() when unlocking, even when that’s not necessary. However, what’s most important is that in the uncontended case, the ideal situation where threads are not attempting to acquire the lock simultaneously, both the wait() and wake_one() calls are entirely avoided.

**Comment by zxch3n** [comment]
Got it. Thanks!
