### ISSUE TITLE
chapter7: 3 typos in ARM instructions in the text

### ISSUE THREAD

**Issue by vni** [m-ou-se/rust-atomics-and-locks#54]
### Type of error

Minor technical mistake

### Location of the error

Chapter7. Use text search to locate them.

ldxar --> ldaxr (load acquire exclusive register) -- this one found twice
stxlr -> stlxr (store release exclusive register)

Found in these paragraphs:
```
As this shows, ARM64 has special versions of its load and store instructions for acquire and release ordering. Unlike an ldr or ldxr instruction, an ldar or ldxar instruction will never be reordered with any later memory operation. Similarly, unlike an str or stxr instruction, an stlr or stxlr instruction will never be reordered with any earlier memory operation.

A fetch-and-modify operation using only Release or Acquire ordering instead of AcqRel uses only one of the stlxr and ldxar instructions, respectively, paired with a regular ldxr or stxr instruction.
```

### Description of the error

These are actually typos in the assembly mnemonics for the arm arch.

**Comment by vni** [comment]
And thank you for the great and insightful book!
It was a pleasure to read it!!! : )

**Comment by m-ou-se** [comment]
> ldxar --> ldaxr (load acquire exclusive register) -- this one found twice
> stxlr -> stlxr (store release exclusive register)

Thanks! Fixed!

> And thank you for the great and insightful book!
> It was a pleasure to read it!!! : )

Really happy to hear that!
