### ISSUE TITLE
Redundant indents

### ISSUE THREAD

**Issue by chengr4** [m-ou-se/rust-atomics-and-locks#58]
### Type of error

Formatting error

### Location of the error

At https://marabos.nl/atomics/building-arc.html#basic-reference-counting

We know the pointer will always point to a valid ArcData<T> as long as the Arc object exists. However, this is not something the compiler knows or checks for us, so accessing the ArcData through the pointer requires unsafe code. We’ll add a private helper function to get from the Arc to the ArcData, since this is something we’ll have to do several times:

```rust
fn data(&self) -> &ArcData<T> {
        unsafe { self.ptr.as_ref() }
    }
```

### Description of the error

Not sure whether this should be reported or not. But I saw redundant indents for

```rust
fn data(&self) -> &ArcData<T> {
        unsafe { self.ptr.as_ref() }
}
```
and beneath

```rust
if self.data().ref_count.fetch_add(1, Relaxed) > usize::MAX / 2 {
            std::process::abort();
}
```

**Comment by m-ou-se** [comment]
Some code blocks are indented, because they are actually snippets that are part of a larger (indented) block, such as an impl block or a function body.

For example,

```rust
    fn data(&self) -> &ArcData<T> {
        unsafe { self.ptr.as_ref() }
    }
```

is indented one level, because that function definition lives inside the `impl Arc<T> { … }` block.

**Comment by chengr4** [comment]
Got it! Thanks for the explanation
