### ISSUE TITLE
A question about the test of `Arc<T>`

### ISSUE THREAD

**Issue by h-a-n-a** [m-ou-se/rust-atomics-and-locks#6]
### The content that the question is about

https://github.com/m-ou-se/rust-atomics-and-locks/blob/af59f9be0744e4adc3362043307083673e30d2f2/src/ch6_arc/s1_basic.rs#L103-L112

### The question

In the test implementation, we use a `Relaxed` ordering to load the result of the current times of drops. However, AFAIK, would `Relaxed` ordering let the compiler or CPU move the instruction above or beneath the dropping of `y`, which results in a failure in the test? Dropping `y` seems not to have _happens-before_  relationship with the last two atomic operations. Would `SeqCst` be a more appropriate one to have?

**Comment by m-ou-se** [comment]
The processor and compiler can reorder operations, but that's only visible from another thread. Within one thread, everything always appears to happen in order. There is a happens before relationship between every line of a single threaded function, basically.

See also https://marabos.nl/atomics/memory-ordering.html#happens-before

**Comment by h-a-n-a** [comment]
> The processor and compiler can reorder operations, but that's only visible from another thread. Within one thread, everything always appears to happen in order. There is a happens before relationship between every line of a single threaded function, basically.
> 
> See also https://marabos.nl/atomics/memory-ordering.html#happens-before

@m-ou-se  This seems a little bit weird to me, in the world of C++, they seem to use _sequenced-before_ the describe this, and in the [C++ reference](https://en.cppreference.com/w/cpp/atomic/memory_order), there is an example of Relaxed ordering:
```c++
// For example, with x and y initially zero,
// Thread 1:
r1 = y.load(std::memory_order_relaxed); // A
x.store(r1, std::memory_order_relaxed); // B
// Thread 2:
r2 = x.load(std::memory_order_relaxed); // C 
y.store(42, std::memory_order_relaxed); // D
```
> is allowed to produce r1 == r2 == 42 because, although A is sequenced-before B within thread 1 and C is sequenced before D within thread 2, nothing prevents D from appearing before A in the modification order of y, and B from appearing before C in the modification order of x. The side-effect of D on y could be visible to the load A in thread 1 while the side effect of B on x could be visible to the load C in thread 2. In particular, **this may occur if D is completed before C in thread 2, either due to compiler reordering or at runtime.**

It's saying that D might be reordered before C, and both C and D come from the same thread, does that meet the same criterion as what you've said? I'm still a little bit confused.
> There is a happens before relationship between every line of a single threaded function, basically.

If the basic _happens-before_ relationship applys, then what's the reason for us to use `Acquire` and `Release` for thread synchronizations since we can just put everything we modified before the signal like this? 

```rust
// init `is_ok` with `false`

thread::spawn(|| {
   do_with_something();
   is_ok.store(true, Relaxed);
})

thread::spawn(|| {
     if is_ok.load(Relaxed) {
        do_with_something_new();
    }
})
```

**Comment by m-ou-se** [comment]
> This seems a little bit weird to me, in the world of C++, they seem to use _sequenced-before_ the describe this

"Sequenced-before" is just one of the two cases of "happens-before".

See https://wg21.link/intro.races#10

> It's saying that D might be reordered before C, and both C and D come from the same thread, does that meet the same criterion as what you've said? I'm still a little bit confused.

That text is talking about reordering at the compiler or hardware level, not about the abstract "happens-before" model. In that example, A happens-before B, and C happens-before D. However, D might still be reordered with C by the compiler or by the hardware, because from a single-threaded perspective, that's impossible to tell from just thread 2.

The rule is that everything within one thread _appears_ to happen in order. Whether it actually does is irrelevant. It only becomes relevant when other threads exist that can observe the operations from the sideline.

> If the basic happens-before relationship applys, then what's the reason for us to use Acquire and Release for thread synchronizations since we can just put everything we modified before the signal like this?

That's explained in https://marabos.nl/atomics/memory-ordering.html#happens-before

To take your example:

```rust
thread::spawn(|| {
   do_with_something(); // (1)
   is_ok.store(true, Relaxed); // (2)
})

thread::spawn(|| {
     if is_ok.load(Relaxed) { // (3)
        do_with_something_new(); // (4)
    }
})
```

Here, (1) happens-before (2), and (3) happens-before (4). However, there is _no_ happens-before relationship between (2) and (3), even if (3) loads `true`! So, (4) has *no* happens-before relationship with neither (2) nor (1). There is no guarantee that the results of (1) are visible on the other thread.

**Comment by h-a-n-a** [comment]
> > This seems a little bit weird to me, in the world of C++, they seem to use _sequenced-before_ the describe this
> 
> "Sequenced-before" is just one of the two cases of "happens-before".
> 
> See https://wg21.link/intro.races#10
> 
> > It's saying that D might be reordered before C, and both C and D come from the same thread, does that meet the same criterion as what you've said? I'm still a little bit confused.
> 
> That text is talking about reordering at the compiler or hardware level, not about the abstract "happens-before" model. In that example, A happens-before B, and C happens-before D. However, D might still be reordered with C by the compiler or by the hardware, because from a single-threaded perspective, that's impossible to tell from just thread 2.
> 
> The rule is that everything within one thread _appears_ to happen in order. Whether it actually does is irrelevant. It only becomes relevant when other threads exist that can observe the operations from the sideline.
> 
> > If the basic happens-before relationship applys, then what's the reason for us to use Acquire and Release for thread synchronizations since we can just put everything we modified before the signal like this?
> 
> That's explained in https://marabos.nl/atomics/memory-ordering.html#happens-before
> 
> To take your example:
> 
> ```rust
> thread::spawn(|| {
>    do_with_something(); // (1)
>    is_ok.store(true, Relaxed); // (2)
> })
> 
> thread::spawn(|| {
>      if is_ok.load(Relaxed) { // (3)
>         do_with_something_new(); // (4)
>     }
> })
> ```
> 
> Here, (1) happens-before (2), and (3) happens-before (4). However, there is _no_ happens-before relationship between (2) and (3), even if (3) loads `true`! So, (4) has _no_ happens-before relationship with neither (2) nor (1). There is no guarantee that the results of (1) are visible on the other thread.

@m-ou-se Really thankful for your quick reply! Can I summarize everything into conclusions as follows?
The _happens before_ relationship within the same thread is generally the order of evaluation from the perspective of code execution order, like what you've described in the book:
> The basic happens-before rule is that everything that happens within the same thread happens in order. If a thread is executing f(); g();, then f() happens-before g(). 

Also, the _happens-before_ relationship within the same thread is as-if they are not re-ordered and applies to the _sequenced-before_ relationship like what the cpp reference said:
https://en.cppreference.com/w/cpp/language/as_if

> 1) Accesses (reads and writes) to [volatile](https://en.cppreference.com/w/cpp/language/cv) objects occur strictly according to the semantics of the expressions in which they occur. **In particular, they are [not reordered](https://en.cppreference.com/w/cpp/atomic/memory_order) with respect to other volatile accesses on the same thread.**

But this _happens-before_ relationship will not be visible across threads as the compiler or the hardware does not have the contract(as they may reorder the instructions) to let other thread to see the value change using the Relaxed ordering. 

The way to make an inter-thread _happens-before_ relationship can be using a more strict memory ordering.

**Comment by m-ou-se** [comment]
Yes, that sounds right. :)

**Comment by h-a-n-a** [comment]
> Yes, that sounds right. :)

Thank you so much! I've been thinking about the "mismatched" re-ordering definition a quite long time. :)
