### ISSUE TITLE
Closure move variable don't always need move keyword.

### ISSUE THREAD

**Issue by sonder-joker** [m-ou-se/rust-atomics-and-locks#7]
### Type of error

Language or grammar issue

### Location of the error

In https://marabos.nl/atomics/basics.html
```rust
let numbers = vec![1, 2, 3];

thread::spawn(move || {
    for n in numbers {
        println!("{n}");
    }
}).join().unwrap();
```
>Here, ownership of numbers is transferred to the newly spawned thread, since we used a move closure. If we had not used the move keyword, the closure would have captured numbers by reference. This would have resulted in a compiler error, since the new thread might outlive that variable.

### Description of the error

In this example, closure already auto move variable even without move keyword. 
```rust
let numbers = vec![1, 2, 3];

thread::spawn(|| {
    for n in numbers {
        println!("{n}");
    }
}).join().unwrap();
```
Above will work well. May another example will be better.

**Comment by m-ou-se** [comment]
Thanks! That for loop was supposed to be `for n in &numbers`, taking the Vec by reference. Looks like the `&` got lost somewhere along the way.

Fixed.
