### ISSUE TITLE
About 'Copy' on chpt. 5 summary

### ISSUE THREAD

**Issue by pedromfedricci** [m-ou-se/rust-atomics-and-locks#8]
### Type of error

Typo

### Location of the error

https://marabos.nl/atomics/building-channels.html#summary

### Description of the error

The summary statement on MaybeUninit<T> tells that users are responsible for **not duplicating Copy data**. I guess it should state that users are responsible for **not duplicating _non-Copy_ data**.
Thank you.

**Comment by m-ou-se** [comment]
Thanks! Fixed!
